services:
  plex:
    container_name: plex
    image: linuxserver/plex
    restart: unless-stopped
    networks:
      - internal_network
    ports:
      - "${PLEX_PORT}:32400"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - plex_config:/config
      - plex_transcode:/transcode
      - ${MEDIA_ROOT}/complete:/data

  sonarr:
    container_name: sonarr
    image: linuxserver/sonarr
    restart: unless-stopped
    networks:
      - nginx_proxy_network
      - internal_network
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      # nginx-proxy variables
      - VIRTUAL_HOST=${SONARR_HOSTNAME}
      - LETSENCRYPT_HOST=${SONARR_HOSTNAME}
      - VIRTUAL_PORT=8989
    volumes:
      - sonarr_config:/config
      - ${MEDIA_ROOT}/complete/tv:/tv
      - ${MEDIA_ROOT}/data:/data
      - /etc/localtime:/etc/localtime:ro

  radarr:
    container_name: radarr
    image: linuxserver/radarr
    restart: unless-stopped
    networks:
      - nginx_proxy_network
      - internal_network
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      # nginx-proxy variables
      - VIRTUAL_HOST=${RADARR_HOSTNAME}
      - LETSENCRYPT_HOST=${RADARR_HOSTNAME}
      - VIRTUAL_PORT=7878
    volumes:
      - radarr_config:/config
      - ${MEDIA_ROOT}/complete/movies:/movies
      - ${MEDIA_ROOT}/data:/data
      - /etc/localtime:/etc/localtime:ro

  prowlarr:
    container_name: prowlarr
    image: linuxserver/prowlarr
    restart: always
    networks:
      - internal_network
    ports:
      - "${PROWLARR_PORT}:9696"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - prowlarr_config:/config

  qbittorrent:
    container_name: qbittorrent
    # There is currently an issue that prevents the latest-tagged image from working with gluetun: https://github.com/qdm12/gluetun/discussions/1562
    image: lscr.io/linuxserver/qbittorrent:libtorrentv1
    restart: unless-stopped
    depends_on:
      - qbittorrent-vpn
    # Place this container inside the VPN container's network so that all traffic is routed through it
    network_mode: "service:qbittorrent-vpn"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - WEBUI_PORT=9091
    volumes:
      - qbittorrent_config:/config
      - ${MEDIA_ROOT}/data/downloads:/data/downloads

  qbittorrent-vpn:
    container_name: qbittorrent-vpn
    image: qmcgaw/gluetun
    restart: unless-stopped
    networks:
      - internal_network
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      # Open the qBittorrent WebUI port
      - "${QBITTORRENT_PORT}:9091"
    environment:
      - VPN_SERVICE_PROVIDER=custom
      - VPN_TYPE=wireguard
      - TZ=${TZ}
    volumes:
      # Wireguard conf file must be located at /gluetun/wireguard/wg0.conf
      - ./qbittorrent-vpn:/gluetun

volumes:
  plex_config:
  plex_transcode:
  sonarr_config:
  radarr_config:
  prowlarr_config:
  qbittorrent_config:

networks:
  internal_network:
  nginx_proxy_network:
    name: ${NGINX_PROXY_NETWORK}
    external: true
