version: "3.8"
services:
  plex:
    container_name: plex
    image: linuxserver/plex
    restart: unless-stopped
    networks:
      - internal_network
    ports:
      - "32400:32400"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ./plex:/config
      - ./plex/transcode:/transcode
      - ${MEDIA_ROOT}/complete:/data

  sonarr:
    container_name: sonarr
    image: linuxserver/sonarr
    restart: unless-stopped
    networks:
      - nginx_network
      - internal_network
    ports:
      - "8989:8989"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - VIRTUAL_HOST=${SONARR_HOSTNAME}
      - LETSENCRYPT_HOST=${SONARR_HOSTNAME}
      - VIRTUAL_PORT=8989
    volumes:
      - ./sonarr:/config
      - ${MEDIA_ROOT}/complete/tv:/tv
      - ${MEDIA_ROOT}/data:/data
      - /etc/localtime:/etc/localtime:ro

  radarr:
    container_name: radarr
    image: linuxserver/radarr
    restart: unless-stopped
    networks:
      - nginx_network
      - internal_network
    ports:
      - "7878:7878"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - VIRTUAL_HOST=${RADARR_HOSTNAME}
      - LETSENCRYPT_HOST=${RADARR_HOSTNAME}
      - VIRTUAL_PORT=7878
    volumes:
      - ./radarr:/config
      - ${MEDIA_ROOT}/complete/movies:/movies
      - ${MEDIA_ROOT}/data:/data
      - /etc/localtime:/etc/localtime:ro

  qbittorrent:
    container_name: qbittorrent
    image: linuxserver/qbittorrent
    restart: unless-stopped
    networks:
      - internal_network
    ports:
      - "9091:9091/tcp"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - WEBUI_PORT=9091
    volumes:
      - ./qbittorrent:/config
      - ${MEDIA_ROOT}/data/downloads:/data/downloads

  prowlarr:
    container_name: prowlarr
    image: linuxserver/prowlarr
    restart: unless-stopped
    networks:
      - internal_network
    ports:
      - "9696:9696"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ./prowlarr:/config

networks:
  internal_network:
  nginx_network:
    external: true
